// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  docs: [
    {
      type: "doc",
      label: "1.1 - Accueil 🏠",
      id: "cours/1.1-accueil",
    },
    {
      type: "doc",
      label: "1.2 - Présentation TP1 🗣️",
      id: "cours/1.1-accueil",
    },
    {
      type: "doc",
      label: "2.1 - Impératif ✊",
      id: "cours/2.1-imperatif",
    },
    {
      type: "doc",
      label: "2.2 - Impératif ✊",
      id: "cours/2.1-imperatif",
    },
    {
      type: "doc",
      label: "3.1 - Librairie standard 📘",
      id: "cours/3.1-std-lib",
    },
    {
      type: "doc",
      label: "3.2 - Librairies tierces 📖",
      id: "cours/3.2-librairies-tierces",
    },
    {
      type: "doc",
      label: "4.1 - Structurer son code 🧱",
      id: "cours/4.1-structure",
    },
    {
      type: "doc",
      label: "4.2 - Intégration 🔨",
      id: "cours/4.2-integration-1",
      className: "04.2-remise-tp1",
    },
    {
      type: "doc",
      label: "5.1 - Formatif",
      id: "cours/5.1-formatif-intra",
    },
    {
      type: "doc",
      label: "5.2 - Examen Intra (30%)",
      id: "cours/5.2-examen-intra",
      className: "examen",
    },
    {
      type: "doc",
      label: "6.1 - Intro Android 🤖",
      id: "cours/6.1-intro-android",
    },
    {
      type: "doc",
      label: "6.2 - Activités et Navigation 🧭",
      id: "cours/6.2-activites",
    },
    {
      type: "doc",
      label: "7.1 - RecyclerView ♻️",
      id: "cours/7.1-recycler",
    },
    {
      type: "doc",
      label: "7.2 - RecyclerView ♻️",
      id: "cours/7.1-recycler",
    },
    {
      type: "doc",
      label: "8.1 - RecyclerView ♻️",
      id: "cours/7.1-recycler",
    },
    {
      type: "doc",
      label: "8.2 - RecyclerView ♻️",
      id: "cours/7.1-recycler",
    },
    {
      type: "doc",
      label: "9.1 - Graphique 📈",
      id: "cours/9.1-graphique",
    },
    {
      type: "doc",
      label: "9.2 - Intégration 🔨",
      id: "cours/9.2-integration-2",
      className: "remise-tp2",
    },
    {
      type: "doc",
      label: "10.1 - Exceptions ⚠️",
      id: "cours/10.1-pile-appels-exceptions",
    },
    {
      type: "doc",
      label: "10.2 - Structurer service 🧱",
      id: "cours/10.2-structure-android",
    },
    {
      type: "doc",
      label: "11.1 - Tiroir de navigation 🗄️",
      id: "cours/11.1-tiroir",
    },
    {
      type: "doc",
      label: "11.2 - Tiroir de navigation 🗄️",
      id: "cours/11.1-tiroir",
    },
    {
      type: "doc",
      label: "12.1 - Tiroir de navigation 🗄️",
      id: "cours/11.1-tiroir",
    },
    {
      type: "doc",
      label: "12.2 - Tests 🧪",
      id: "cours/12.2-tests",
    },
    {
      type: "doc",
      label: "13.1 - Tests 🧪",
      id: "cours/12.2-tests",
    },
    {
      type: "doc",
      label: "13.2 - Multilingue 🌐",
      id: "cours/13.2-multilingue",
    },
    {
      type: "doc",
      label: "14.1 - Intégration 🔨",
      id: "cours/14.1-integration-3",
    },
    {
      type: "doc",
      label: "14.2 - Intégration 🔨",
      id: "cours/14.1-integration-3",
      className: "remise-tp3",
    },
    {
      type: "doc",
      label: "15.1 - Formatif",
      id: "cours/15.1-formatif-final",
    },
    {
      type: "doc",
      label: "15.2 - Examen Final (30%)",
      id: "cours/15.2-examen-final",
      className: "examen",
    },
  ],
  tp: [
    { type: "doc", label: "TP1 - KotCrawler", id: "tp/tp1" },
    { type: "doc", label: "TP2 - Interface graphique Android", id: "tp/tp2" },
    { type: "doc", label: "TP3 - Appli Android", id: "tp/tp3" },
  ],
  recettes: [{ type: "autogenerated", dirName: "02-recettes" }],
};

module.exports = sidebars;
